### PR TITLE
Init Animation for Logo

### PR DESCRIPTION
**Pull request by grayghostvisuals**
If you want jQuery out of the picture I'll let you handle that ;) Let me know if you want this motion or not otherwise I'll readjust.

### CODE REVIEW

**Comment by grayghostvisuals** [comment]
Here is another variation with a bit more adjustments with the motion and speed. [http://codepen.io/grayghostvisuals/full/ogPxjq/](http://codepen.io/grayghostvisuals/full/ogPxjq/)

**Comment by anselmh** [comment]
Hey, thanks man, was away yesterday so couldn’t reply. It would be really great if we could avoid jQuery indeed.

Apart from that, I also like the speedy version but it refuses to play fully (it’s being cropped) in Firefox? Not sure if this is the code or only is in CodePen (had issues with Firefox and CodePen before with some pens).

**Comment by grayghostvisuals** [comment]
There's actually a bug in TweenMax 1.16 when using ``rotationY`` and ``opacity`` together. I reported this to Jack and Carl at GreenSock and just waiting on a reply. This should have been fixed in 1.16, but apparently is still causing problems in Safari and Firefox. Standby Houston.

**Comment by grayghostvisuals** [comment]
@anselmh So uncomment each option in the JS window to see the variations in action [http://codepen.io/grayghostvisuals/pen/ogPxjq](http://codepen.io/grayghostvisuals/pen/ogPxjq)

It seems the spec does not support 3D transforms on SVG so option no.3 will not animate in Safari the same as it will in Chrome and Firefox. I suggest comparing each options across the major 3. Options no.1 & no.2 are using 2D transforms and work as expected across the board with identical behavior.

LMK which one you want :)

**Comment by anselmh** [comment]
So I couldn’t see a huge difference between v1 and 3 honestly but I like them both. v2 is too fancy in my opinion.
So either v1 or v3 will win. What do you prefer?

**Comment by grayghostvisuals** [comment]
> It seems the spec does not support 3D transforms on SVG so option no.3 will not animate in Safari the same as it will in Chrome and Firefox. I suggest comparing each options across the major 3. Options no.1 & no.2 are using 2D transforms and work as expected across the board with identical behavior.

**Comment by grayghostvisuals** [comment]
So basically your choice has to be no2 unless you don't mind Safari only animating opacity of the motion as it happens to be with no3. I agree I like no3 the best so far.

**Comment by anselmh** [comment]
Sorry seems I misunderstood the comment. But, to be honest, I don’t think the Safari issue is a problem. It’s still nice in Safari so I’d opt for v3 still.

**Comment by grayghostvisuals** [comment]
@anselmh All set for you based on this entire discussion and requests \m/

**Comment by anselmh** [comment]
Merged in manually at https://github.com/anselmh/wdrl/commit/3ddc0329e4f8ec0bf2e1d581b2aa451c2a276ad2 – thanks so much @grayghostvisuals for doing this! :)

**Pull request closed without merging**
